Repository RHEcosystemAppEng/cluster-iq-console, pull requests merged in 2024-12, with the labels that each got.

#24 V0.2
  README.md
  VERSION
  package-lock.json
  package.json
  src/app/AccountDetails/AccountDetails.tsx
  src/app/ClusterDetails/ClusterDetails.tsx
  src/app/Clusters/Clusters.tsx
  src/app/ServerDetails/ServerDetails.tsx
  src/app/Servers/Servers.tsx
  src/app/types/types.tsx
  src/app/utils/parseFuncs.tsx
  src/app/utils/renderStatusLabel.tsx
  src/index.html
Labels: documentation, enhancement

#32 fix: typo in podman command
  Makefile
Labels: bug

#35 feat: added action button to power on/power off cluster
  src/app/ClusterDetails/ClusterDetails.tsx
Labels: enhancement, good first issue

#46 feat: add modal confirmation window to the power on/off dropdown
  src/app/ClusterDetails/ClusterDetails.tsx
Labels: enhancement

#44 feat: add dummy API calls for powering on/off cluster
  src/app/services/api.js
Labels: enhancement

#51 fix: remove PageSection width constraints to eliminate UI gap
  src/app/AccountDetails/AccountDetails.tsx
  src/app/ClusterDetails/ClusterDetails.tsx
  src/app/ServerDetails/ServerDetails.tsx
Labels: bug

#54 feat: refactor Accounts page
  src/app/Accounts/Accounts.tsx
  src/app/Accounts/types.ts
Labels: chore

#56 chore: delete unused assets
  src/assets/favicon.ico
  src/assets/index.html
  src/assets/logo192.png
  src/assets/logo512.png
  src/assets/manifest.json
  src/assets/robots.txt
Labels: chore
