Repository RHEcosystemAppEng/cluster-iq-console, pull requests merged in 2025-05, with the labels that each got.

#84 Release 0.4.1
  package-lock.json
  package.json
  src/app/AccountDetails/components/AccountDescriptionList.tsx
  src/app/ClusterDetails/components/ClusterDetailsOverview.tsx
  src/app/types/types.tsx
Labels: documentation, enhancement, chore

#88 chore: update ClusterIQ title link to redirect to console overview page
  src/app/AppLayout/AppLayout.tsx
Labels: chore

#91 feat: add 'About' modal window
  deployments/containerfiles/Containerfile
  eslint.config.js
  src/app/AppLayout/AboutModal.tsx
  src/app/AppLayout/AppLayout.tsx
  src/app/constants.ts
  src/assets/modal_background.png
  src/vite-env.d.ts
  vite.config.ts
Labels: enhancement

#92 feat: add user logout functionality
  src/app/AppLayout/AppLayout.tsx
Labels: enhancement
